on:
  push:
    branches:
      - master

jobs:
    build-test-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: run-scripts
          run: |
            npm install --force
            npm run build
        - name: Deploy
          uses:
            crazy-max/ghaction-github-pages@v1
          with:
            target_branch: gh-pages
            build_dir: build
          env:
            GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_PORTFOLIO_WEBSITE }}
